export enum SocketState {
  NEW = "NEW",
  LOADING = "LOADING",
  UPLOADED = "UPLOADED",
  PROCESSING = "PROCESSING",
  RUNNING_ANALYTICS = "RUNNING_ANALYTICS",
  COMPILING = "COMPILING",
  DONE = "DONE",
  FAILED = "FAILED"
}
